_extends: .github

version: 1
rules:
  - upstream:
      repo:
        owner: sporkfed
        name: test-source-1
      branch: main
      path: source.yml
    target:
      path: test-source-1/source.yml
      branch: main

