name: "Yaml Lint"
on:  # yamllint disable-line
  - "push"
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo apt-get update
          sudo apt-get install -y tree
      - run: |
          pwd
          ls -lah ./
          tree
          cat -A ./test-source-1/source.yml

          sudo tree ./.git
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ${{ github.workspace }}
