name: "Yaml Lint"
on:  # yamllint disable-line
  - "push"
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo apt-get update
          sudo apt-get install -y tree
      - run: |
          shopt -s globstar
          options+=("${INPUT_FILE_OR_DIR:-.}")
          shopt -u globstar

          echo "${options}"
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
