name: "Yaml Lint"
on:  # yamllint disable-line
  - "push"
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          pwd
          ls -lah

          sudo apt-get update
          sudo apt-get install -y tree

          tree logs/refs/remotes/origin/
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
